### ISSUE TITLE
Unable to load files on Windows

### ISSUE THREAD

**Issue by matt-allan** [matt-allan/renoise-exs24#1]
```
main.lua:121: attempt to perform arithmetic on local ‘last_slash_pos’ (a nil value)
stack traceback:
main.lua:121: in function main.lua:97"
```

Reported via https://forum.renoise.com/t/new-tool-3-1-exs24/49835/6

Most likely the basename/dirname logic here needs to account for windows backslash as well as unix forward slash.

https://github.com/yuloh/renoise-exs24/blob/fc37f99ce94cc5a40a8beae40e9939cd000cc420/main.lua#L120

**Comment by MichaelGallo** [comment]
I have a working fix for Windows, interested?

**Comment by matt-allan** [comment]
Sure @MichaelGallo, feel free to open a pull request. Thanks!

**Comment by MichaelGallo** [comment]
The weird thing is I had to change not only the slash, but also the endianness of one of the values ("sig") to be able to load my files. I tested in on my Mac with a GarageBand instrument, and everything seems to be working there as well.
I have it in my local branch, but I don't have permission to push it to the repo.
Maybe I'm missing something obvious, but this is my first contribution to a repo where I wasn't previously invited.

**Comment by matt-allan** [comment]
If you follow [these instructions](https://help.github.com/en/github/getting-started-with-github/fork-a-repo) to fork a repo you should be able to push your branch to your fork. Then you can [open a PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) from your fork.

**Comment by MichaelGallo** [comment]
Thanks! Done.

**Comment by matt-allan** [comment]
This should be fixed now
