### ISSUE TITLE
Newest EXS24 tool? Renoise Tools says "Dec 30th 2018"

### ISSUE THREAD

**Issue by esaruoho** [matt-allan/renoise-exs24#3]
Hi, I went to https://www.renoise.com/node/858 and it says that the newest version of EXS24 tool is Dec 30th 2018.

Is this really the newest version? Can it be updated?

**Comment by matt-allan** [comment]
Yes, that's the newest version. There haven't been any changes to release since then.

You can see all the releases here: https://github.com/matt-allan/renoise-exs24/releases
