### ISSUE TITLE
how to run on macOS?

### ISSUE THREAD

**Issue by esaruoho** [matt-allan/renoise-exs24#6]
hi, how do i run with this macOS?

**Comment by matt-allan** [comment]
I'm working on a new release now. I doubt this version works with the current renoise api.

**Comment by matt-allan** [comment]
If you want to try a development build you can download it here: https://github.com/matt-allan/renoise-exs24/actions/runs/9510311791

To install just double click. To use it find an .exs file in the sidebar and double click to load, just like a normal xrni instrument.

**Comment by matt-allan** [comment]
I published a new release. I'm going to close this but please follow up in the forums if you have any issues!
